import { Article } from './types';

// Auto-generated by scripts/migrate-jekyll-posts.mjs — DO NOT EDIT MANUALLY
import { article as artigoAksAcr } from './2023-02-05-artigo-aks-acr';
import { article as artigoAksVolume } from './2023-02-05-artigo-aks-volume';
import { article as artigoPipelinesCiCd } from './2023-02-05-artigo-pipelines-ci-cd';
import { article as artigoPrometheus } from './2023-08-14-artigo-prometheus';
import { article as explorandoIaGenerativa } from './2023-10-27-explorando-ia-generativa';
import { article as participacoes } from './2023-10-28-participacoes';
import { article as eventos } from './2023-10-30-eventos';
import { article as mentoriacloud23 } from './2023-11-06-mentoriacloud23';
import { article as foundationCloud } from './2023-12-04-foundation-cloud';
import { article as wellArchitectFoundationCloud } from './2023-12-11-well-architect-foundation-cloud';
import { article as foundationLz } from './2024-01-02-foundation-lz';
import { article as devopsFoundationCloud } from './2024-01-08-devops-foundation-cloud';
import { article as azureBackupVirtualMachines } from './2024-01-15-azure-backup-virtual-machines';
import { article as finopsFoundationCloud } from './2024-01-15-finops-foundation-cloud';
import { article as observabilidadeFoundationCloud } from './2024-01-17-observabilidade-foundation-cloud';
import { article as greenComputingFoundationCloud } from './2024-01-24-green-computing-foundation-cloud';
import { article as _2meetcncf } from './2024-02-22-2meetcncf';
import { article as kcdsp24 } from './2024-02-25-kcdsp24';
import { article as globalAzure24 } from './2024-05-18-global-azure24';
import { article as azureStaticWebApps } from './2024-05-24-azure-static-web-apps';
import { article as tcBc24 } from './2024-06-02-tc-bc24';
import { article as criacaoVm } from './2024-06-05-criacao-vm';
import { article as configRepository } from './2024-06-06-config-repository';
import { article as cursoAz900 } from './2024-06-10-curso-az-900';
import { article as kubertenes } from './2024-06-17-kubertenes';
import { article as podcast } from './2024-06-23-podcast';
import { article as talkTdc } from './2024-06-25-talk-tdc';
import { article as antesCloudNativeFundacaoSolida } from './2024-07-14-antes-cloud-native-fundacao-solida';
import { article as fundacaoSolidaFinops } from './2024-07-14-fundacao-solida-finops';
import { article as monitoriaObservabilidadeCloud } from './2024-07-14-monitoria-observabilidade-cloud';
import { article as azureWorkbooks } from './2024-07-16-azure-workbooks';
import { article as azureFloripa } from './2024-07-21-azure-floripa';
import { article as cncfsc } from './2024-07-21-cncfsc';
import { article as comuDodFloripa } from './2024-07-21-comu-dod-floripa';
import { article as eventododFloripa } from './2024-07-21-eventodod-floripa';
import { article as kcdFloripa24 } from './2024-07-21-kcd-floripa24';
import { article as iaGen } from './2024-07-25-ia-gen';
import { article as guiaCriacaoVmsAzure } from './2024-07-26-guia-criacao-vms-azure';
import { article as azureWorkbooksFinops } from './2024-08-04-azure-workbooks-finops';
import { article as _6rs } from './2024-08-11-6rs';
import { article as estrategiasModernizacao6rs } from './2024-08-22-estrategias-modernizacao-6rs';
import { article as cursoDp900 } from './2024-09-02-curso-dp-900';
import { article as codecon } from './2024-09-11-codecon';
import { article as zsh } from './2024-09-12-zsh';
import { article as tls } from './2024-10-08-tls';
import { article as agil } from './2024-10-29-agil';
import { article as automatizandoInfraestruturaMetodologiasAgeis } from './2024-10-29-automatizando-infraestrutura-metodologias-ageis';
import { article as sustentabilityDay } from './2024-10-31-sustentability-day';
import { article as mvpDay } from './2024-11-02-mvp-day';
import { article as tftec2024 } from './2024-11-04-tftec2024';
import { article as tcFloripa24 } from './2024-11-10-tc-floripa24';
import { article as codeIsland24 } from './2024-11-24-code-island24';
import { article as azPolicy } from './2025-01-09-az-policy';
import { article as azurePolicyVisaoCompleta } from './2025-01-11-azure-policy-visao-completa';
import { article as translatek8s } from './2025-03-23-translatek8s';
import { article as sqlsat25 } from './2025-04-06-sqlsat25';
import { article as azbkpshouldenabledvm } from './2025-04-12-azbkpshouldenabledvm';
import { article as carreiraInternacional } from './2025-05-18-carreira-internacional';
import { article as globalAzure25 } from './2025-05-18-global-azure25';
import { article as globalAzure25pres } from './2025-05-18-global-azure25pres';
import { article as mvpConfBlu } from './2025-05-23-mvp-conf-blu';
import { article as terraformAssociateArtigo } from './2025-08-03-terraform-associate-artigo';
import { article as hack } from './2025-08-20-hack';
import { article as dodCrtb25 } from './2025-09-01-dod-crtb25';
import { article as dodMeetupaws } from './2025-09-30-dod-meetupaws';
import { article as tdcGreenops } from './2025-10-04-tdc-greenops';
import { article as az700 } from './2025-10-06-az-700';
import { article as mvpCrtb } from './2025-10-12-mvp-crtb';
import { article as wsdDevops } from './2025-10-19-wsd-devops';

export const allArticles: Article[] = [
  artigoAksAcr,
  artigoAksVolume,
  artigoPipelinesCiCd,
  artigoPrometheus,
  explorandoIaGenerativa,
  participacoes,
  eventos,
  mentoriacloud23,
  foundationCloud,
  wellArchitectFoundationCloud,
  foundationLz,
  devopsFoundationCloud,
  azureBackupVirtualMachines,
  finopsFoundationCloud,
  observabilidadeFoundationCloud,
  greenComputingFoundationCloud,
  _2meetcncf,
  kcdsp24,
  globalAzure24,
  azureStaticWebApps,
  tcBc24,
  criacaoVm,
  configRepository,
  cursoAz900,
  kubertenes,
  podcast,
  talkTdc,
  antesCloudNativeFundacaoSolida,
  fundacaoSolidaFinops,
  monitoriaObservabilidadeCloud,
  azureWorkbooks,
  azureFloripa,
  cncfsc,
  comuDodFloripa,
  eventododFloripa,
  kcdFloripa24,
  iaGen,
  guiaCriacaoVmsAzure,
  azureWorkbooksFinops,
  _6rs,
  estrategiasModernizacao6rs,
  cursoDp900,
  codecon,
  zsh,
  tls,
  agil,
  automatizandoInfraestruturaMetodologiasAgeis,
  sustentabilityDay,
  mvpDay,
  tftec2024,
  tcFloripa24,
  codeIsland24,
  azPolicy,
  azurePolicyVisaoCompleta,
  translatek8s,
  sqlsat25,
  azbkpshouldenabledvm,
  carreiraInternacional,
  globalAzure25,
  globalAzure25pres,
  mvpConfBlu,
  terraformAssociateArtigo,
  hack,
  dodCrtb25,
  dodMeetupaws,
  tdcGreenops,
  az700,
  mvpCrtb,
  wsdDevops
].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

export function getArticleBySlug(slug: string): Article | undefined {
  return allArticles.find(article => article.slug === slug);
}

export function getArticlesByCategory(category: string): Article[] {
  return allArticles.filter(article => article.category === category);
}

export function getArticlesByTag(tag: string): Article[] {
  return allArticles;
}

export function getRecentArticles(limit: number = 5): Article[] {
  return allArticles.slice(0, limit);
}

export function getAllCategories(): string[] {
  const categories = allArticles.map(article => article.category);
  return Array.from(new Set(categories)).sort();
}

export const articles = allArticles;
